# Generated by Django 2.2.4 on 2019-08-27 04:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_one', models.CharField(choices=[('sfshock', 'San Francisco Shock'), ('vtitans', 'Vancouver Titans'), ('nyexcelsior', 'New York Excelsior'), ('hspark', 'Hangzhou Spark'), ('lagladiators', 'Los Angeles Gladiators'), ('areign', 'Atlanta Reign'), ('lspitfire', 'London Spitfire'), ('gcharge', 'Guangzhou Charge'), ('pfusion', 'Philadelphia Fusion'), ('sdynasty', 'Seoul Dynasty'), ('sdragons', 'Shanghai Dragons'), ('chunters', 'Chengdu Hunters'), ('lavaliant', 'Los Angeles Valiant'), ('peternal', 'Paris Eternal'), ('dfuel', 'Dallas Fuel'), ('houtlaws', 'Houston Outlaws'), ('tdefiant', 'Toronto Defiant'), ('wjustice', 'Washington Justice'), ('buprising', 'Boston Uprising'), ('fmayhem', 'Florida Mayhem')], max_length=255)),
                ('team_two', models.CharField(choices=[('sfshock', 'San Francisco Shock'), ('vtitans', 'Vancouver Titans'), ('nyexcelsior', 'New York Excelsior'), ('hspark', 'Hangzhou Spark'), ('lagladiators', 'Los Angeles Gladiators'), ('areign', 'Atlanta Reign'), ('lspitfire', 'London Spitfire'), ('gcharge', 'Guangzhou Charge'), ('pfusion', 'Philadelphia Fusion'), ('sdynasty', 'Seoul Dynasty'), ('sdragons', 'Shanghai Dragons'), ('chunters', 'Chengdu Hunters'), ('lavaliant', 'Los Angeles Valiant'), ('peternal', 'Paris Eternal'), ('dfuel', 'Dallas Fuel'), ('houtlaws', 'Houston Outlaws'), ('tdefiant', 'Toronto Defiant'), ('wjustice', 'Washington Justice'), ('buprising', 'Boston Uprising'), ('fmayhem', 'Florida Mayhem')], max_length=255)),
                ('season', models.PositiveIntegerField(default=2)),
                ('stage', models.PositiveIntegerField()),
                ('week', models.PositiveIntegerField()),
                ('day', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Video')),
            ],
        ),
    ]
